php-estudo:
  build: .
#  links:
#    - db:mysql
  ports:
    - "8081:80"
  volumes:
    - ./www:/var/www/html
db:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: "123456"
    MYSQL_MAJOR: 5.6
    MYSQL_VERSION: 5.6.50-1debian9
  networks:
    default:
      aliases:
        - mysql
